### ISSUE TITLE
Linux - expects to find 64bit library

### ISSUE THREAD

**Issue by mungewell** [cmbruns/pyopenvr#26] opened 2016-12-01 05:56 UTC
SteamVR can be installed under the Linux client, looks like pyopenvr expects library to be 64bit... when it isn't (at least on my machine).

    simon@morkmobile:~/pyopenvr-git$ python src/samples/hello.py
    Traceback (most recent call last):
      File "src/samples/hello.py", line 5, in <module>
        import openvr
      File "/usr/local/lib/python2.7/dist-packages/openvr/__init__.py", line 39, in <module>
        _openvr = cdll.LoadLibrary(_openvr_lib_name)
      File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
        return self._dlltype(name)
      File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: libopenvr_api_64.so: cannot open shared object file: No such file or directory
    simon@morkmobile:~/pyopenvr-git$ dpkg --list | grep steam
    ii  steam-launcher                         1.0.0.53                                      all          Launcher for the Steam software distribution service
    simon@morkmobile:~/pyopenvr-git$ find ~/.local/ -name 'libopenvr*'
    /home/simon/.local/share/Steam/ubuntu12_32/libopenvr_api.so

**Comment by cmbruns-hhmi** [comment] 2016-12-19 17:59
The file "libopenvr_api_64.so" should be installed with pyopenvr, in the same folder as __init__.py. The openvr project provides only a 64-bit linux library; no 32-bit version at the moment. https://github.com/ValveSoftware/openvr/tree/master/bin PyOpenVR uses its own copy of the openvr api shared library, so it would match the exact version of the API wrapped by the python binding. 

I wonder whether setting LD_LIBRARY_PATH could help sidestep this problem.

Did you install pyopenvr via "pip install pyopenvr"?

Are you running 64-bit python?

Sorry I have not been testing pyopenvr on Linux. Your help in sorting out these issues is appreciated.

**Comment by eric-schleicher** [comment] 2017-03-28 20:51
I'm interested in getting this to work as well.  Attempting to create a  ros node based on this library.

Am i understanding it correctly that i would need to make a copy of the `libopenvr_api_64.so` file in the same folder as this library?  

willing to try.

Please advise.

**Comment by cmbruns** [comment] 2017-03-28 21:27
@eric-schleicher Are you trying to use pyopenvr on a 32-bit linux system? That's what this issue is about.

If you have somehow obtained a 32-bit openvr shared library, you could experiment with naming it libopenvr_api_32.so, and placing it in the pyopenvr folder. Unfortunately pyopenvr has not been well tested even on 64-bit linux systems. But you might find some enlightenment in issue #5 https://github.com/cmbruns/pyopenvr/issues/5#issuecomment-245012925

Have you at least got regular C++ openvr code working on your linux machine, and are now trying to get pyopenvr working?

**Comment by eric-schleicher** [comment] 2017-03-29 04:36
no sorry this will be x64

On Tue, Mar 28, 2017 at 2:27 PM, Christopher Bruns <notifications@github.com

**Comment by eric-schleicher** [comment] 2017-04-11 05:13
ok, i did end up running into this exact despite being on x64 ubuntu 16.04LTS and useing python3.5 with pip3 to perform the install.

![image](https://cloud.githubusercontent.com/assets/8261783/24893044/b215996c-1e35-11e7-8b8e-5e524bf67ae9.png)

I was able to get it to run on windows; and i was just reproducing the logical steps on linux, which is my target platform.  

Now following the comment on issue #5.  will update if i find a solution

**Comment by claytmcneil** [comment] 2017-05-19 13:53
I ran into an issue loading the library as well. The problem is that the mechanism used to load the library does not look at PATH, but rather looks at LD_LIBRARY_PATH. However, since that particular variable has to be set before python is invoked, there's not way (that I can tell) to set it in the script.

So rather than trying to set a PATH, I just changed the script to use an absolute path when on Linux.

**Comment by kazoo-kmt** [comment] 2017-06-22 00:04
Hi @claytmcneil, I'm having a trouble including the PATH (I described the detail here https://github.com/cmbruns/pyopenvr/issues/5#issuecomment-310237824). Could you share the process you took in detail and the potential solution for this issue?

**Comment by claytmcneil** [comment] 2017-06-22 16:56
@kazoo-kmt Rather then set the PATH, I specified the full path of the lib in the open. Under openvr/__init__.py, I modified last line of the snippet below:


`# Add current directory to PATH, so we can load the DLL from right here.
os.environ['PATH'] += os.pathsep + os.path.dirname(__file__)
_openvr = cdll.LoadLibrary(os.path.join("/absolute/path/to/library", _openvr_lib_name))`

**Comment by cmbruns** [comment] 2019-02-21 01:58
Fixed by fix for #36

**Closed by cmbruns** 2019-02-21 01:58 UTC
