### ISSUE TITLE
Hickups in tracking and/or rendering

### ISSUE THREAD

**Issue by paulmelis** [cmbruns/pyopenvr#15] opened 2016-06-16 14:17 UTC
With the samples I tried, basically the GLUT- and SDL-based ones, I get hickups, where there is a noticeable jump and/or lag in the view. The SteamVR Frame Timing window nicely shows peaks at these moments:

![image](https://cloud.githubusercontent.com/assets/1408287/16119862/b9dd98cc-33dd-11e6-8463-2551ee291a04.png)

I haven't figured out yet from the plots if this is due to the python samples not using the OpenVR API correctly (e.g. blocking when they shouldn't). It can't be anything to do with the rendering taking too much time as even the pink_world.py example shows this behaviour and it hardly renders anything.

This isn't fully pyopenvr's fault, as I see the same pattern with the hellovr_opengl C++ sample in the OpenVR repo. In fact, every sample based on OpenVR I tried (there aren't that many actually online) show the same hickups. Now, this might have something to do with our setup, but all applications in SteamVR we try work fine (e.g The Lab or Tilt brush) and show smooth Frame Timing. The only simple OpenGL sample that works slightly better is this one (http://casual-effects.blogspot.nl/2016/03/opengl-sample-codeand-openvr-sample-code.html), but it still shows hickups, but less often. There's even an issue in the OpenVR repo that mentions the sample isn't fully up-to-date, but that's mostly to the way distortion is handled (https://github.com/ValveSoftware/openvr/issues/42).

So does anyone else see similar hickups? Is this due to incorect use of the OpenVR API with respect to blocking (or not) in the main tracking and rendering loop? Are there (py)openvr-based examples that work smoothly?

Setup: Core i7 @ 3.50 GHz, Windows 8.1 Enterprise 64-bit, latest SteamVR beta, Geforce GTX Titan, with latest NVidia drivers, Python 2.7.6 (32-bit), OpenVR 1.0.1, Vive consumer edition (i.e. not a developer pre-release)

**Comment by cmbruns** [comment] 2016-06-16 14:33
@paulmelis Nice analysis. How do I launch that frame timing window, so I can perform the same analysis on my system?

**Comment by cmbruns** [comment] 2016-06-16 15:18
I think I know what the problem is. The demo apps are blocking at the refresh rate of the desktop monitor, which is probably slower than the refresh rate of the VR headset.
Try removing the "On-screen render" block near line 105 of pink_world.py (glClear() and glutSwapBuffers()).
I usually test on a 120 Hz desktop monitor, so I have usually not seen this problem. But if I drag the desktop mirror to a slower monitor, I observe a similar stuttering.
Some possible ways to avoid this problem:
1) don't mirror the scene to the screen
2) use some cleverer way to mirror the scene to the screen asynchronously
3) disable vsync
4) mirror to the screen less frequently

**Comment by cmbruns** [comment] 2016-06-16 16:00
The near-term solution for this problem is for me to turn off double buffering and swapping in the framework examples. This approach is working for me for GLUT, at least, in my local working copy. I found I needed to add a "glFlush()" command in the OpenVR renderer to make desktop rendering work.

**Comment by cmbruns** [comment] 2016-06-16 17:19
I have succeeded in avoiding stalling in the glfw, glut, qt, and sdl frameworks by disabling double buffering in the desktop mirror rendering. (in my local dev environment; I will commit later). But I cannot get it to both display and not stall with the wx framework.

**Comment by cmbruns** [comment] 2016-06-16 18:23
This is mostly resolved in revision 1fd67a9b390e8b54dfc95ebec419f5c22fa5d837
The remaining issue with the wx framework is recorded in a new issue #16

**Closed by cmbruns** 2016-06-16 18:23 UTC

**Comment by paulmelis** [comment] 2016-06-16 19:01
Thank you, that was indeed it and disabling sync-to-vblank removed the hickups! It's silly that we didn't connect the dots on our end, as we noticed that the on-desktop view showed no hickups at all. Duh...
